IBX-7968: Mitigate issues reported by community
ibexa/http-cache pull request #46
Opened 2024-03-18 16:04 UTC by dabrt

| Question           | Answer |
| ------------------ | ------------------ |
| **JIRA issue**     | [IBX-7968](https://issues.ibexa.co/browse/IBX-7968) |
| **Type**           | Misc |
| **Target version** | main |
| **BC breaks**      | no |
| **Doc needed**     | no |

Community reports issues when using Varnish 6.6.
We need to cleatly state what version is supported.

- [x] Ask for Code Review.

2024-03-19 07:44 UTC, vidarl requested changes
varnish5.vcl is for varnish 6.0LTS ( not for varnish 7.1)
varnish7.vcl is for varnish 7.1

So varnish5.vcl should technically be renamed varnish6.vcl, but that might be considered a BC break, so maybe copy it?

2024-03-19 10:39 UTC, dabrt commented on docs/varnish/vcl/varnish5.vcl
> +// - Varnish 6.0LTS or 7.1 (6.0LTS recommended, and is what we mainly test against)
```suggestion
// - Varnish 6.0LTS
```

2024-03-19 11:51 UTC, vidarl approved these changes
In Ibexa DXP 5.0, `varnish5.vcl` should be removed, or at least made deprecated

2024-03-19 15:57 UTC, mnocon reviewed
I agree that we need to clear the confusion around supported versions, but I'm afraid that adding the varnish6 file and maintaining both of them (varnish5, varnish6) at the same time won't work - I feel that that eventually someone forgets to update one of them.

I'm not sure what the best solution is (if we can't rename the file then I'd probably just keep the filenames varnish5 and varnish6 and made it right in v5 🤔 )

2024-03-19 15:57 UTC, mnocon commented on docs/varnish/.DS_Store
This file should be removed (I recommend adding the .DS_STORE files to the global .gitignore, we can discuss this next week)

2024-03-20 10:30 UTC, dabrt commented on docs/varnish/.DS_Store
Done

2024-03-20 10:33 UTC, dabrt commented
> I agree that we need to clear the confusion around supported versions, but I'm afraid that adding the varnish6 file and maintaining both of them (varnish5, varnish6) at the same time won't work - I feel that that eventually someone forgets to update one of them.

@alongosz We have confronting opinions from Vidar and Marek. What's your say here?

2024-03-21 13:56 UTC, alongosz reviewed
@dabrt @mnocon @vidarl
I have a suggestion. Let's make a symlink to varnish5.vcl instead. It looks weird on the github diff and I need to check how this behaves on windows, but this is seems what Symfony is doing as well to avoid duplicating recipes.

In a long term I think the place of these files should be in recipes and they should be placed in custom projects. But not sure where exactly and that's for 5.0

@dabrt one more thing, I see you've stated that you're targeting main version. Do you indeed intend to make this change for 5.0 only? main is for 5.0, yet from the context of the discussion I'm not sure if that was your intention

2024-03-21 14:16 UTC, alongosz commented
> It looks weird on the github diff and I need to check how this behaves on windows

update: sadly it doesn't work on windows (at leastOOTB)... we need to think what to do with it.

2024-03-22 08:00 UTC, vidarl commented
May idea was to do the renaming in 5.0 only at least.. But it might be that we can only deprecate it in 5.0, and to the actuall renaming in v6?

2024-03-22 08:38 UTC, alongosz commented
> May idea was to do the renaming in 5.0 only at least.. But it might be that we can only deprecate it in 5.0, and to the actuall renaming in v6?

We should rather rename it in 5.0.

2024-03-22 10:08 UTC, alongosz commented
@dabrt we've discussed this within PHP Team and due to issues with symlinks decided to keep both files as you've originally intended, but I've added an explanation note on the top of each file. The changes have been already applied to the PR.
// FYI @mnocon @vidarl 

@dabrt the only issue remains is that these changes now target future 5.0 branch (main) and I'm not sure if this was your intention. If it was then we just can remove varnish5.vcl.

2024-03-28 07:46 UTC, dabrt commented
> @dabrt the only issue remains is that these changes now target future 5.0 branch (main) and I'm not sure if this was your intention. If it was then we just can remove varnish5.vcl.

Please advise which bundle branch I should clone these changes to, to include it in 4..6 as well.

2024-03-29 13:01 UTC, alongosz approved these changes

2024-03-29 13:05 UTC, konradoboza approved these changes

2024-03-29 13:12 UTC, Nattfarinn reviewed
Shouldn't it be rebranded by the way? There are few `sub ez_*` and `call ez_*`that could be renamed.

2024-03-29 13:26 UTC, alongosz commented
> Shouldn't it be rebranded by the way? There are few `sub ez_*` and `call ez_*`that could be renamed.

If we can safely do it, we should. 
@vidarl are there any BC concerns here? E.g. is it possible for someone to rely on thouse subroutine names or are they internal to a vcl file?

2024-04-02 06:36 UTC, vidarl commented
> If we can safely do it, we should. @vidarl are there any BC concerns here? E.g. is it possible for someone to rely on those subroutine names or are they internal to a vcl file?

Clients can do al kind of changes in the .vlc file, so strictly speaking, any change we do in vcl can potentially be a BC.
But it is fair to call those sub routines that are named `ez_*` as internal. I would not consider changing their name in 5.0 a problem. But maybe keep them as-is in existing releases

2024-04-05 06:59 UTC, mnocon approved these changes

2024-04-05 12:42 UTC, adamwojs commented
@Nattfarinn We will handle rebranding as part of the 5.0 scope

2024-04-05 12:42 UTC, adamwojs approved these changes

2024-04-09 14:50 UTC, alongosz approved these changes
Thx for the input, Vidar :+1:

2024-04-09 15:00 UTC, alongosz commented
Given this is a copy of existing and working VCL, no QA required here. Merging as-is. Thanks everyone for the input.

2024-04-09 15:03 UTC, merged